# Generated by Django 5.2.7 on 2025-10-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'Service'), ('project', 'Project')], default='service', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('short_summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='published', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('service_category', models.CharField(blank=True, choices=[('essential', 'الخدمات الأساسية'), ('community', 'الخدمات المجتمعية'), ('complementary', 'الخدمات المكملة')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('allow_volunteers', models.BooleanField(default=True)),
                ('volunteers_required', models.PositiveIntegerField(default=0)),
                ('volunteers_committed', models.PositiveIntegerField(default=0)),
                ('allow_donations', models.BooleanField(default=True)),
                ('target_units_label', models.CharField(blank=True, max_length=64)),
                ('target_units', models.PositiveIntegerField(default=0)),
                ('target_beneficiaries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='programs', to='core.audiencesegment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.program')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['kind', 'status'], name='core_progra_kind_a4eef0_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['service_category', 'is_active'], name='core_progra_service_db8800_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['scheduled_date'], name='core_progra_schedul_5e585a_idx'),
        ),
    ]
