# Generated by Django 5.2.7 on 2025-10-17 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 10 أرقام.', regex='^\\d{10}$')])),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('age_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صالح.', regex='^\\+?\\d{8,15}$')])),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('joined_hijri', models.CharField(blank=True, max_length=32)),
                ('education_level', models.CharField(blank=True, choices=[('hs', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('other', 'أخرى')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.interest')),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'متقدم'), ('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('on_hold', 'معلقة'), ('completed', 'مكتملة'), ('withdrawn', 'منسحب'), ('rejected', 'مرفوض')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_hours', models.PositiveIntegerField(default=0)),
                ('actual_hours', models.PositiveIntegerField(default=0)),
                ('org_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('volunteer_note', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_applications', to='core.program')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('on_hold', 'معلقة'), ('done', 'منجزة'), ('cancelled', 'ملغاة')], default='new', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('planned_hours', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_region', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='volunteers.volunteerapplication')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='volunteers.volunteertask')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['city', 'region'], name='volunteers__city_ef0d40_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['education_level'], name='volunteers__educati_de40a4_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['status'], name='volunteers__status_664c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['due_date'], name='volunteers__due_dat_05c351_idx'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(fields=('program', 'profile'), name='uniq_application_per_program'),
        ),
    ]
