# Generated by Django 5.2.7 on 2025-10-17 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='national_id',
            field=models.CharField(help_text='رقم الهوية الوطنية السعودية (10 أرقام).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون مكونًا من 10 أرقام.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(help_text='رقم الجوال السعودي، مثل 05XXXXXXXX أو +9665XXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يبدأ بـ 05 أو +9665 ويحتوي على 9 أرقام بعد ذلك.', regex='^(\\+9665\\d{8}|05\\d{8})$')]),
        ),
    ]
