# Generated by Django 5.2.7 on 2025-10-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('volunteers', '0002_alter_volunteerprofile_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['applied_at'], name='volunteers__applied_87d4b0_idx'),
        ),
    ]
